name: 'Test'
on: ['push', 'pull_request']

jobs:
  test:
    name: 'Vim ${{ matrix.vim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        vim_version:
          - 'head'
          - 'v8.2.3253'
        platform: ['Linux', 'MacOS', 'Windows']

        include:
          - platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - platform: 'Windows'
            os: 'windows-latest'
            download: 'always'

      fail-fast: false

    runs-on: '${{ matrix.os }}'
    timeout-minutes: 10

    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Setup Vim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_version: '${{ matrix.vim_version }}'
          download: '${{ matrix.download }}'
      - name: 'Show Vim version'
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: 'Setup themis.vim'
        uses: 'actions/checkout@v2'
        with:
          repository: 'thinca/vim-themis'
          ref: 'v1.5.5'
          path: 'themis'
      - name: 'Run test'
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./themis/bin/themis --reporter dot
